<?php
namespace Nipponjob\AccueilBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function myFindOneByTitre(){
        return $this->createQueryBuilder('a')->where('a.titre = :titre')->setParameter('titre', 'Celui-ci')->getQuery()->getSingleResult();
    }
    public function ohYeah(){
    return $this->_em->createQuery('SELECT a.titre FROM NipponjobAccueilBundle:Article a')->getResult();
    }
}
