jms_security_extra:
    secure_all_services: false
    expressions: true
    
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Nipponjob\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
         entity: { class: Nipponjob\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: acces
                check_path: acces_verif
            logout:
                path:   deconnexion
                target: /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }