parameters:
#    nipponjob_user.example.class: Nipponjob\UserBundle\Example

services:
#    nipponjob_user.example:
#        class: %nipponjob_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
