nipponjob_accueil_index:
    path:     /
    defaults: { _controller: NipponjobAccueilBundle:Accueil:index }
nipponjob_accueil_contact:
    path:     /contact
    defaults: { _controller: NipponjobAccueilBundle:Accueil:contact }